use_default_settings:
  engines:
    remove:
      - wikidata
      - ahmia
      - torch
      - brave
      - brave.images
      - brave.videos
      - brave.news
      - duckduckgo
      - karmasearch
      - "karmasearch videos"

server:
  secret_key: "hva-searxng-local-only"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json
